name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build-deploy-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup jdk-17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Build and Test with Maven
        working-directory: backend
        run: mvn clean test package

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
            name: jar-file
            path: backend/target/*.jar

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: NeuroArt
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}/backend/target/*.jar'
          env: 'OPENAI_KEY=${{ secrets.OPENAI_KEY }}'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp restart --name NeuroArt --resource-group neuroArtResourceGroup
